[package]
name = "nomad-api"
version.workspace = true
edition.workspace = true

[dependencies]
nomad-types = { path = "../types" }

eyre.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

aide = { version = "0.15", features = [
    "scalar",
    "axum",
    "axum-json",
    "macros",
] }
axum = { version = "0.8.1", features = ["macros"] }

